//
//  ViewController.swift
//  Text character counter
//
//  Created by Christian Croona on 15/03/16.
//  Copyright © 2016 christian. All rights reserved.
//

import UIKit

class ViewController: UIViewController, UITextViewDelegate {

    
    //Outlets
   
    @IBOutlet weak var characterCountLabel: UILabel!
    @IBOutlet weak var textView: UITextView!
  
    //Functions
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // set the label to show start value of characters left
        self.characterCountLabel.hidden = false
        // delegate tracks changes in the text input
         self.textView.delegate = self
    }
    //This is autogenerated when you write "func textView"
    func textView(textView: UITextView, shouldChangeTextInRange range: NSRange, replacementText text: String) -> Bool {
        // Define newText as a NSString to be used with the NSRange
        var newText: NSString = textView.text!
        newText = (newText as NSString).stringByReplacingCharactersInRange(range, withString: text)
        
        // writing "guard let" is the eqvivelent of writing a traditional if/else statement since swift 2.0
        guard let text = textView.text else { return true }
        let newLength = text.characters.count - range.length
       
        // Writes the current length of newText into the label
        self.characterCountLabel.text = String(70 - newText.length)
    
        // allowing text input as long as newLength is less than 70
        return newLength <= 68
    }
   }

